<?php
/**
* 	
*/

# Define namespace
namespace WCFE\Modules\Editor\View\Editor\Templates;

# No direct access
defined('ABSPATH') or die( WCFE\NO_DIRECT_ACCESS_MESSAGE );

?>
<div id="wcfe-confirm-save-message">
	<div id="wcfe-confirm-save-message-dialog">
		<ul class="wcfe-thickbox-errors-list"></ul>
		<img class="ajax-loader-image" src="<?php echo WP_PLUGIN_URL . '/wp-config-file-editor/Modules/Editor/View/Editor/Media/Images/ajax-loader.gif'; ?>" width="32px" height="31px">
		<div id="wcfe-restore-note">
			<div class="warning-image">
				<img class="success-status-image" width="95px" height="95px" src="<?php echo WP_PLUGIN_URL . '/wp-config-file-editor/Modules/Editor/View/Editor/Media/Images/agt_action_success_256.png'; ?>" alt="<?php $this->_e( 'Successed' ) ?>" />
				<img class="warning-status-image" width="95px" height="95px" src="<?php echo WP_PLUGIN_URL . '/wp-config-file-editor/Modules/Editor/View/Editor/Media/Images/dialog-warning.png' ?>" alt="<?php $this->_e( 'Warning' ) ?>" />
			</div>
			<div id="wcfe-restore-section">
				<p><?php $this->_e( 'Please keep this window opened until testing the site in another window as restore link cannot be obtained later. ') ?>
				<?php $this->_e( 'Here is a link to discard all changes you made in the last SAVE process' ) ?>: <a target="_blank" href="#" class="wcfe-restore-link"><?php $this->_e( 'Restore Backup' ) ?></a></p>
			</div>
			<ul id="wcfe-update-config-file-warning-notes">
			  <li><?php $this->_e( 'Current wp-config.php file has been back-ed up to be restored later if needed' ) ?></li>
			  <li><?php $this->_e( 'Its recommended to test the site is not broken after updating wp-config.php file' ) ?></li>
			  <li><?php $this->_e( 'Please test the site is still working by opening new browser window/tab' ) ?></li>
			  <li><?php $this->_e( 'Its recommended to leave this screen opened until testing the site in another TAB/WINDOW' ) ?></li>
			  <li><?php $this->_e( 'After closing this form the backup will be deleted' ) ?></li>
			  <li><?php $this->_e( 'Restore Url is valid for only 1 hour' ) ?></li>
			  <li>
			  	<?php $this->_e( 'You can close this window either from Done button or from close button' ) ?>-
			  	<ul class="done-button-note">
			  		<li><?php $this->_e( 'Close button won\'t delete emergency backup created when this window is opened, it won\'t not also refresh Form page, therefore it might not reflect the correct state on the server' ) ?></li>
			  		<li><?php $this->_e( 'Done button (recommended) will delete emergency backup and won\'t refresh form page to reflect server state. This is more secure as it deletes the backup' ) ?></li>
			  	</ul>
			  </li>
				<li><?php $this->_e( 'This process will replace wp-config.php file content with content generated from the values you\'ve entered in the form.' ) ?></p>
				<li><?php $this->_e( 'The process is totally replace the old code with new code generated by Config File Editor Plugin and all the code you had in wp-config.php will be replaced.' ) ?></li>
				<li><?php $this->_e( 'This is risky process and might stop the site' ) ?></li>
				<li><?php $this->_e( 'This process never touch your Database or any file except wp-config.php file, in case the site is stopped you just need to revert wp-config.php file back to old values') ?></li>
				<li>
					<?php $this->_e( 'Please don\'t keep if you care about one of the following' ) ?>:
					<ul>
				    <li><?php $this->_e( 'wp-config.php contains custom code -- not originally bundled with normal Wordpress installation' ) ?></li>
						<li><?php $this->_e( 'You\'re not entirly positive of the values you changed') ?></li>
						<li><?php $this->_e( 'You manually added wp-config.php constants that not supported by Config File Editor plugin' ) ?></li>
				  </ul>				
				</li>
			</ul>
	  </div>

	</div>
	<input type="button" id="wcfe-update-config-file" value="Update" />
	<input type="button" id="wcfe-update-done" value="Done" />
</div>