<?php
/**
* 	
*/

# Define namespace
namespace WCFE\Modules\Editor\View\Editor\Templates;

# No direct access
defined('ABSPATH') or die(WCFE\NO_DIRECT_ACCESS_MESSAGE);

?>
<div id="wcfe-confirm-save-message">
	<div id="wcfe-confirm-save-message-dialog">
		<ul class="wcfe-thickbox-errors-list"></ul>
		<div id="wcfe-restore-note">
		
			<div class="warning-image">
				<img src="<?php echo WP_PLUGIN_URL . '/wp-config-file-editor/Modules/Editor/View/Editor/Media/Images/dialog-warning.png' ?>" alt="Warning" />
			</div>
			<div id="wcfe-restore-section">
				<p>Please keep this window opened until testing the site in another window as restore link cannot be obtained later.
				Click <a href="#" class="wcfe-restore-link">Restore Backup</a> to discard all changes you made in the last SAVE process</p>
			</div>
			<ul id="wcfe-update-config-file-warning-notes">
			  <li>Current wp-config.php file has been back-ed up to be restored later if needed</li>
			  <li>Its recommended to test the site is not broken after updating wp-config.php file</li>
			  <li>Please test the site is still working by opening new browser window/tab</li>
			  <li>Its recommended to leave this screen opened until testing the site in another TAB/WINDOW</li>
			  <li>After closing this form the backup will be deleted</li>
			  <li>Restore Url is valid for only 1 hour</li>
				<li>This process will replace wp-config.php file content with content generated from the values you've entered in the form.</p>
				<li>The process is totally replace the old code with new code generated by Config File Editor Plugin and all the code you had in wp-config.php will be replaced.</li>
				<li>This is risky process and might stop the site</li>
				<li>This process never touch your Database or any file except wp-config.php file, in case the site is stopped you just need to revert wp-config.php file back to old values</li>
				<li>
					Please don't keep if you care about one of the following reasons:
					<ul>
				    <li>wp-config.php contains custom code -- not originally bundled with normal Wordpress installation</li>
						<li>You're not 100% positive of the values you changed</li>
						<li>You manually added wp-config.php constants that not supported by Config File Editor plugin</li>
				  </ul>				
				</li>
			</ul>
	  </div>

	</div>
	<input type="button" id="wcfe-update-config-file" value="Update" />
</div>